"""
Reads the GIS layer's pre-generated outputs (gis/generate_analytics.py,
gis/generate_geo_data.py). No on-the-fly computation here — these files
need geopandas/shapely to produce and are regenerated by the Python GIS
pipeline, not by the API.

get_provincias_from_db() is a hybrid: province_kpis.json supplies the 24
static provinces (incl. geographic metadata for the 19 with no clients),
while the DB overrides financial fields for the 5 commercially active ones.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

from fastapi import HTTPException
from sqlalchemy import case, func, select
from sqlalchemy.orm import Session

from backend.core.config import get_settings

settings = get_settings()

_REPO_ROOT = Path(__file__).resolve().parents[2]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

import gis.geo_utils as gu  # noqa: E402


def _read_json(path: Path) -> dict | list:
    if not path.exists():
        raise HTTPException(
            status_code=503,
            detail=f"{path.name} not found — run `python -m gis.generate_analytics` "
                    f"(and `python -m gis.generate_geo_data` for provincias) first.",
        )
    return json.loads(path.read_text(encoding="utf-8"))


def get_provincias() -> list[dict]:
    return _read_json(settings.geo_dir / "province_kpis.json")


def get_provincias_from_db(db: Session) -> list[dict]:
    """Hybrid: 24 provinces from province_kpis.json; financial fields overridden
    from DB for the 5 provinces that have real client data."""
    from backend.models.orm import DimCliente, FactLogistica, FactVentas

    base: list[dict] = list(get_provincias())

    # Client counts and churn per province
    cli_stmt = (
        select(
            DimCliente.provincia,
            func.count().label("n_clientes"),
            func.sum(case((DimCliente.activo.is_(True), 1), else_=0)).label("n_activos"),
        )
        .select_from(DimCliente)
        .where(DimCliente.provincia.isnot(None))
        .group_by(DimCliente.provincia)
    )

    # Revenue and margin per province (all-time, consistent with GIS pipeline)
    rev_stmt = (
        select(
            DimCliente.provincia,
            func.sum(FactVentas.total_ars).label("revenue_ars"),
            func.sum(FactVentas.margen_bruto_ars).label("margen_sum"),
        )
        .select_from(FactVentas)
        .join(DimCliente, FactVentas.cliente_id == DimCliente.cliente_id)
        .group_by(DimCliente.provincia)
    )

    # OTIF per province (all-time) — avg is equivalent to sum/count for 0/1 indicator
    otif_stmt = (
        select(
            DimCliente.provincia,
            (
                func.avg(
                    case((FactLogistica.estado == "Entregado", 1), else_=0)
                    * case((FactLogistica.dias_demora == 0, 1), else_=0)
                ) * 100
            ).label("otif_pct"),
        )
        .select_from(FactLogistica)
        .join(DimCliente, FactLogistica.cliente_id == DimCliente.cliente_id)
        .group_by(DimCliente.provincia)
    )

    db_data: dict[str, dict] = {}

    for r in db.execute(cli_stmt).fetchall():
        prov = gu.normalize_province(r.provincia)
        n_c, n_a = int(r.n_clientes), int(r.n_activos)
        db_data[prov] = {
            "n_clientes": n_c,
            "n_activos": n_a,
            "churn_score": round((1 - n_a / n_c) * 100, 2) if n_c else 0.0,
        }

    total_revenue = 0.0
    for r in db.execute(rev_stmt).fetchall():
        prov = gu.normalize_province(r.provincia)
        rev = float(r.revenue_ars or 0)
        margen_sum = float(r.margen_sum or 0)
        if prov not in db_data:
            db_data[prov] = {}
        db_data[prov]["revenue_ars"] = round(rev, 2)
        db_data[prov]["margen_pct"] = round(margen_sum / rev * 100, 2) if rev else 0.0
        total_revenue += rev

    for prov in db_data:
        rev = db_data[prov].get("revenue_ars", 0.0)
        db_data[prov]["revenue_pct"] = round(rev / total_revenue * 100, 2) if total_revenue else 0.0

    for r in db.execute(otif_stmt).fetchall():
        prov = gu.normalize_province(r.provincia)
        if prov in db_data:
            db_data[prov]["otif_pct"] = round(float(r.otif_pct or 0), 2)

    for item in base:
        prov_key = gu.normalize_province(item.get("nombre", ""))
        if prov_key in db_data:
            item.update(db_data[prov_key])

    return base


def get_hotspots() -> dict:
    return _read_json(settings.gis_outputs_dir / "hotspots.geojson")


def get_coverage() -> list[dict]:
    return _read_json(settings.gis_outputs_dir / "coverage_score.json")


def get_territories() -> dict:
    return _read_json(settings.gis_outputs_dir / "territories.geojson")
