"""
Reads the GIS layer's pre-generated outputs (gis/generate_analytics.py,
gis/generate_geo_data.py). No on-the-fly computation here — these files
need geopandas/shapely to produce and are regenerated by the Python GIS
pipeline, not by the API.
"""
from __future__ import annotations

import json
from pathlib import Path

from fastapi import HTTPException

from backend.core.config import get_settings

settings = get_settings()


def _read_json(path: Path) -> dict | list:
    if not path.exists():
        raise HTTPException(
            status_code=503,
            detail=f"{path.name} not found — run `python -m gis.generate_analytics` "
                    f"(and `python -m gis.generate_geo_data` for provincias) first.",
        )
    return json.loads(path.read_text(encoding="utf-8"))


def get_provincias() -> list[dict]:
    return _read_json(settings.geo_dir / "province_kpis.json")


def get_hotspots() -> dict:
    return _read_json(settings.gis_outputs_dir / "hotspots.geojson")


def get_coverage() -> list[dict]:
    return _read_json(settings.gis_outputs_dir / "coverage_score.json")


def get_territories() -> dict:
    return _read_json(settings.gis_outputs_dir / "territories.geojson")
