"""
AgroNova v3.0 — Backend Platform.

Run from repo root:
    uvicorn backend.main:app --reload

Docs: /docs (Swagger UI), /redoc.
"""
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from backend.api.routers import gis, health, kpis, logistics, ml
from backend.core.config import get_settings

settings = get_settings()

app = FastAPI(
    title=settings.app_name,
    version=settings.version,
    description=(
        "Cliente-servidor platform for AgroNova. GIS/logistics endpoints read "
        "data/gis_outputs/ (generated by gis/generate_analytics.py); KPI "
        "endpoints aggregate data/csv/ directly; ML endpoints are documented "
        "placeholders until ml/models/train_*.py are actually run."
    ),
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.cors_origins,
    allow_methods=["GET"],
    allow_headers=["*"],
)

app.include_router(health.router)
app.include_router(kpis.router)
app.include_router(gis.router)
app.include_router(ml.router)
app.include_router(logistics.router)


@app.get("/", tags=["health"])
def root() -> dict:
    return {"name": settings.app_name, "version": settings.version, "docs": "/docs"}
